/*********************************************************************
*                     SEGGER Microcontroller GmbH                    *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter (Demoversion) for emWin version 5.50         *
*        Compiled Oct 24 2019, 09:15:38                              *
*                                                                    *
*        (c) 1998 - 2019 Segger Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: font_kaiti_30.c                                       *
* Font:        华文楷体                                              *
* Height:      30                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  30                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: E:\y25测试平台\fonts_src.txt                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont_kaiti_30;

/* Start of unicode area <Basic Latin> */
static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_kaiti_30_0042[ 60] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXX_____,
  ___XX___,__XXX___,
  ___XX___,___XX___,
  ___XX___,___XXX__,
  ___XX___,___XXX__,
  ___XX___,___XX___,
  ___XX___,__XX____,
  ___XXXXX,XXX_____,
  ___XX___,__XXX___,
  ___XX___,____XX__,
  ___XX___,____XXX_,
  ___XX___,____XXX_,
  ___XX___,____XXX_,
  ___XX___,____XXX_,
  ___XX___,____XX__,
  ___XXX__,___XX___,
  _XXXXXXX,XXXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_kaiti_30_0043[ 90] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,XXXXXX__,________,
  ______XX,_____XXX,________,
  ____XXX_,______XX,________,
  ___XXX__,_______X,________,
  ___XX___,________,________,
  __XXX___,________,________,
  __XX____,________,________,
  _XXX____,________,________,
  _XXX____,________,________,
  _XXX____,________,________,
  _XXX____,________,________,
  _XXX____,________,________,
  _XXX____,________,________,
  __XXX___,________,________,
  ___XX___,________,________,
  ___XXX__,_______X,________,
  _____XX_,______XX,________,
  _______X,XXXXXXX_,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_kaiti_30_0044[ 90] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  XXXXXXXX,XXXXX___,________,
  ___XX___,___XXXX_,________,
  ___XX___,_____XXX,X_______,
  ___XX___,______XX,XX______,
  ___XX___,_______X,XX______,
  ___XX___,________,XXX_____,
  ___XX___,________,XXX_____,
  ___XX___,________,XXX_____,
  ___XX___,________,XXX_____,
  ___XX___,________,XXX_____,
  ___XX___,________,XXX_____,
  ___XX___,________,XXX_____,
  ___XX___,________,XX______,
  ___XX___,_______X,XX______,
  ___XX___,______XX,X_______,
  ___XX___,_____XXX,________,
  _XXXXXXX,XXXXXX__,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_kaiti_30_0049[ 60] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  _XXXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_kaiti_30_0053[ 60] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,X_______,
  ___XX___,_XX_____,
  __X_____,__X_____,
  _XX_____,__X_____,
  _XX_____,__X_____,
  __XX____,________,
  __XXXX__,________,
  ____XXXX,________,
  _____XXX,XX______,
  _______X,XXX_____,
  ________,_XXX____,
  ________,__XX____,
  _X______,__XX____,
  _XX_____,__XX____,
  _XX_____,__XX____,
  _XXXX___,_XX_____,
  ___XXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_kaiti_30_0055[ 90] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,____XX__,XX______,
  _XXXXXXX,______XX,________,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  ___XX___,______X_,________,
  ____XX__,______X_,________,
  _____XX_,_____X__,________,
  ______XX,XXXXX___,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_kaiti_30_0061[ 60] = { /* code 0061, LATIN SMALL LETTER A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ___X__XX,X_______,
  __X____X,X_______,
  _XX____X,X_______,
  _X_____X,X_______,
  _____XXX,X_______,
  ____X__X,X_______,
  ___X___X,X_______,
  __X____X,X_______,
  _XX___XX,X_______,
  _XXXXX_X,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_kaiti_30_0069[ 30] = { /* code 0069, LATIN SMALL LETTER I */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  ________,
  ________,
  ________,
  ___X____,
  __XX____,
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  _XXXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_kaiti_30_006B[ 60] = { /* code 006B, LATIN SMALL LETTER K */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X____,________,
  XXXX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX___X,XXX_____,
  __XX____,X_______,
  __XX__XX,________,
  __XX_X__,________,
  __XXXXX_,________,
  __XX__XX,________,
  __XX___X,X_______,
  __XX____,XX______,
  __XX____,_X______,
  XXXXX__X,XXXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_kaiti_30_006C[ 30] = { /* code 006C, LATIN SMALL LETTER L */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_kaiti_30_006D[ 90] = { /* code 006D, LATIN SMALL LETTER M */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___X____,________,________,
  __XX__XX,XX___XXX,XX______,
  _XXXXX__,_XX_X___,XXX_____,
  __XX____,__XX____,_XX_____,
  __XX____,__XX____,_XX_____,
  __XX____,__XX____,_XX_____,
  __XX____,__XX____,_XX_____,
  __XX____,__XX____,_XX_____,
  __XX____,__XX____,_XX_____,
  __XX____,__XX____,_XX_____,
  __XX____,__XX____,_XX_____,
  XXXXXX__,XXXXXX_X,XXXXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_kaiti_30_006E[ 60] = { /* code 006E, LATIN SMALL LETTER N */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X____,________,
  ___X__XX,XXX_____,
  __XXXX__,_XXX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  XXXXXX__,XXXXXX__,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontfont_kaiti_30_CharInfo[12] = {
   {  16,  16,  2, acGUI_Fontfont_kaiti_30_0042 } /* code 0042 */
  ,{  17,  17,  3, acGUI_Fontfont_kaiti_30_0043 } /* code 0043 */
  ,{  21,  21,  3, acGUI_Fontfont_kaiti_30_0044 } /* code 0044 */
  ,{   9,   9,  2, acGUI_Fontfont_kaiti_30_0049 } /* code 0049 */
  ,{  13,  13,  2, acGUI_Fontfont_kaiti_30_0053 } /* code 0053 */
  ,{  19,  19,  3, acGUI_Fontfont_kaiti_30_0055 } /* code 0055 */
  ,{  11,  11,  2, acGUI_Fontfont_kaiti_30_0061 } /* code 0061 */
  ,{   6,   6,  1, acGUI_Fontfont_kaiti_30_0069 } /* code 0069 */
  ,{  13,  13,  2, acGUI_Fontfont_kaiti_30_006B } /* code 006B */
  ,{   6,   6,  1, acGUI_Fontfont_kaiti_30_006C } /* code 006C */
  ,{  21,  21,  3, acGUI_Fontfont_kaiti_30_006D } /* code 006D */
  ,{  14,  14,  2, acGUI_Fontfont_kaiti_30_006E } /* code 006E */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_kaiti_30_Prop7 = {
   0x006B /* first character */
  ,0x006E /* last character  */
  ,&GUI_Fontfont_kaiti_30_CharInfo[  8] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_kaiti_30_Prop6 = {
   0x0069 /* first character */
  ,0x0069 /* last character  */
  ,&GUI_Fontfont_kaiti_30_CharInfo[  7] /* address of first character */
  ,&GUI_Fontfont_kaiti_30_Prop7 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_kaiti_30_Prop5 = {
   0x0061 /* first character */
  ,0x0061 /* last character  */
  ,&GUI_Fontfont_kaiti_30_CharInfo[  6] /* address of first character */
  ,&GUI_Fontfont_kaiti_30_Prop6 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_kaiti_30_Prop4 = {
   0x0055 /* first character */
  ,0x0055 /* last character  */
  ,&GUI_Fontfont_kaiti_30_CharInfo[  5] /* address of first character */
  ,&GUI_Fontfont_kaiti_30_Prop5 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_kaiti_30_Prop3 = {
   0x0053 /* first character */
  ,0x0053 /* last character  */
  ,&GUI_Fontfont_kaiti_30_CharInfo[  4] /* address of first character */
  ,&GUI_Fontfont_kaiti_30_Prop4 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_kaiti_30_Prop2 = {
   0x0049 /* first character */
  ,0x0049 /* last character  */
  ,&GUI_Fontfont_kaiti_30_CharInfo[  3] /* address of first character */
  ,&GUI_Fontfont_kaiti_30_Prop3 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_kaiti_30_Prop1 = {
   0x0042 /* first character */
  ,0x0044 /* last character  */
  ,&GUI_Fontfont_kaiti_30_CharInfo[  0] /* address of first character */
  ,&GUI_Fontfont_kaiti_30_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontfont_kaiti_30 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,30 /* height of font  */
  ,30 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontfont_kaiti_30_Prop1}
  ,23 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,17 /* Height of capital characters */
};

